apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: finflow
  labels:
    app: fraud-detection
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: finflow
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: fraud-detection
