apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-api
  namespace: finflow
  labels:
    app: transaction-api
  annotations:
    # GKE Workload Identity
    iam.gke.io/gcp-service-account: finflow-transaction-api@PROJECT_ID.iam.gserviceaccount.com
