apiVersion: v1
kind: ConfigMap
metadata:
  name: finflow-config
  namespace: finflow
  labels:
    app.kubernetes.io/part-of: finflow
data:
  kafka-bootstrap-servers: "finflow-kafka-bootstrap.finflow-kafka.svc.cluster.local:9092"
  fraud-threshold: "0.7"
  payment-processor-url: "http://payment-processor.finflow.svc.cluster.local"
  fraud-detection-url: "http://fraud-detection.finflow.svc.cluster.local"
  account-service-url: "http://account-service.finflow.svc.cluster.local"
  notification-service-url: "http://notification-service.finflow.svc.cluster.local"
