apiVersion: v1
kind: Namespace
metadata:
  name: finflow
  labels:
    app.kubernetes.io/part-of: finflow
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finflow-kafka
  labels:
    app.kubernetes.io/part-of: finflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: finflow-monitoring
  labels:
    app.kubernetes.io/part-of: finflow
