apiVersion: v1
kind: Service
metadata:
  name: payment-processor
  namespace: finflow
  labels:
    app: payment-processor
    app.kubernetes.io/name: payment-processor
    app.kubernetes.io/part-of: finflow
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: payment-processor
